import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dashboard from '../components/Dashboaard/Dashboard'
import AuthIn from '../components/Auth/Auth-In'
import { useState, useEffect } from 'react';
import useLocalStorage from '../Hooks/useLocalStorage'
import { ContactsProvider } from '../Context/ContactsProvider'
import { ConversationsProvider } from '../Context/ConversationsProvider'
import { SocketProvider } from '../Context/SocketProvider'

export default function Home() {
// const [token, setToken] = useLocalStorage()
const [token, setToken] = useState()

const tokenValidation = async() => {
  let myToken
  if(typeof window !== "undefined"){
   await  localStorage.getItem('token') === null && localStorage.getItem('token') === undefined ?
  localStorage.setItem('CrDevToken', token) :  setToken(localStorage.getItem("CrDevToken"))
  // myToken = localStorage.getItem("CrDevToken")
  setToken(localStorage.getItem("CrDevToken"))

  }
  console.log(myToken)
}

// useEffect(() => {
//   let myToken
//   localStorage.getItem('CrDevToken') != null && localStorage.getItem('CrDevToken') != undefined && localStorage.getItem('CrDevToken') != "undefined" ?
//   myToken = localStorage.getItem("CrDevToken") :  localStorage.setItem("CrDevToken", token)
//   myToken = localStorage.getItem("CrDevToken")
//   // setToken(localStorage.getItem("CrDevToken"))
//   setToken(myToken)
//   console.log(myToken)
// }, [token])


const dashboard = (
  <SocketProvider id ={token}>
  <ContactsProvider>
    <ConversationsProvider id={token}>
    <Dashboard id={token} /> 
    </ConversationsProvider>
  </ContactsProvider>
  </SocketProvider>

)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Dashboard /> */}
      
      {
        token ? dashboard : <AuthIn onTokenSubmit={setToken} /> 
      }
    </div>
  )
}
